In [73]:
import pandas as pd
data={
    "Name":["Ahmed","Ali","Mona"],
    "Age":[22,24,30],
    "City":["Cairo","Giza","Qena"]
}
df=pd.DataFrame(data,index=[1,2,3])
print(df)

    Name  Age   City
1  Ahmed   22  Cairo
2    Ali   24   Giza
3   Mona   30   Qena

In [74]:
df["Age"].mean()

np.float64(25.333333333333332)

In [75]:
s1=pd.Series([33,44,55],index=(5,6,7,))
print(s1)

pop_dictionary={
    "California":338849050,
    "Texas":46787656,
    "New york":5432678
}
type(pop_dictionary)
pop_ser=pd.Series(pop_dictionary)
pop_ser
type(pop_ser)

5    33
6    44
7    55
dtype: int64

pandas.core.series.Series

In [76]:
df["Name"][1]

'Ahmed'

In [85]:
ramen_df=pd.read_csv('ramen-ratings.csv')
ramen_df.head()

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN

In [78]:
# we use iloc to get data using the indecies of colomns and rows

#Select the first 5 rows and the colomns [brand ,variety ,style]
ramen_df.iloc[0:5,1:4]

            Brand                                            Variety Style
0       New Touch                          T's Restaurant Tantanmen    Cup
1        Just Way  Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...  Pack
2          Nissin                      Cup Noodles Chicken Vegetable   Cup
3         Wei Lih                      GGE Ramen Snack Tomato Flavor  Pack
4  Ching's Secret                                    Singapore Curry  Pack

In [79]:
# Select the last 10 rows in two ways
ramen_df.tail(10)         #way 1
ramen_df.iloc[-10:,:]     #way 2

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
2570,10,Smack,Vegetable Beef,Pack,USA,1.5,NaN
2571,9,Sutah,Cup Noodle,Cup,South Korea,2,NaN
2572,8,Tung-I,Chinese Beef Instant Rice Noodle,Pack,Taiwan,3,NaN
2573,7,Ve Wong,Mushroom Pork,Pack,Vietnam,1,NaN
2574,6,Vifon,Nam Vang,Pack,Vietnam,2.5,NaN
2575,5,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.5,NaN
2576,4,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1,NaN
2577,3,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2,NaN
2578,2,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2,NaN
2579,1,Westbrae,Miso Ramen,Pack,USA,0.5,NaN

In [80]:
# we use loc to get data using the names of colomns

ramen_df.loc[:,["Brand","Style","Stars"]]

               Brand Style Stars
0          New Touch   Cup  3.75
1           Just Way  Pack     1
2             Nissin   Cup  2.25
3            Wei Lih  Pack  2.75
4     Ching's Secret  Pack  3.75
...              ...   ...   ...
2575           Vifon  Bowl   3.5
2576         Wai Wai  Pack     1
2577         Wai Wai  Pack     2
2578         Wai Wai  Pack     2
2579        Westbrae  Pack   0.5

[2580 rows x 3 columns]

## The diffrence between loc and iloc

In [81]:
ramen_df.iloc[1:4]            # implicit indexing (deals with the default indexes)

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN

In [82]:
ramen_df.loc[1:4]             # explicit indexing (deals with the entered indexes)

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN

* To explore the data , ask interesting questions 
    
     so Let us have a look at the Ramen dishes served in Taiwan

In [83]:
Taiwan=ramen_df["Country"] == "Taiwan"
ramen_df.loc[Taiwan]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
40,2540,Wei Lih,GGE Noodle Snack Wheat Crackers Mexican Spicy,Pack,Taiwan,3.25,NaN
65,2515,Uni-President,Man Han Feast Spicy Beef Flavor Instant Noodles,Bowl,Taiwan,5,NaN
68,2512,Mom's Dry Noodle,Dan Dan Noodle,Pack,Taiwan,5,NaN
...,...,...,...,...,...,...,...
2500,80,Unif / Tung-I,Artificial Chicken,Pack,Taiwan,3.5,NaN
2512,68,Wei Lih,Jah Jan Mien Instant Noodle With Fried Soybean...,Pack,Taiwan,4,NaN
2522,58,Ve Wong,A-One Bun Tom Shrimp,Pack,Taiwan,3,NaN
2537,43,Kim Ve Wong,Jaopai Series: Vegetarian Instant Noodles,Bowl,Taiwan,0,NaN
2572,8,Tung-I,Chinese Beef Instant Rice Noodle,Pack,Taiwan,3,NaN

Let us have a look at the ramen dishes wich have ratings above than average

In [84]:
ramen_df["Stars"].astype(float)      # it does not work because there is missing data wich (unrated)

ValueError: could not convert string to float: 'Unrated'

In [116]:
ramen_df= ramen_df.loc[ramen_df["Stars"]!="Unrated"]       #RUN THE CSV FILE CODE

In [117]:
# So now we will just work on the data which is rated

ramen_df["Stars"]= ramen_df["Stars"].astype(float)

In [92]:
mean = ramen_df["Stars"].mean()

In [94]:
ramen_df[ramen_df["Stars"] > mean]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN
5,2575,Samyang Foods,Kimchi song Song Ramen,Pack,South Korea,4.75,NaN
6,2574,Acecook,Spice Deli Tantan Men With Cilantro,Cup,Japan,4.00,NaN
7,2573,Ikeda Shoku,Nabeyaki Kitsune Udon,Tray,Japan,3.75,NaN
...,...,...,...,...,...,...,...
2557,23,Nissin,Top Ramen Creamy Chicken,Pack,USA,4.50,NaN
2558,22,Nongshim,Ansungtangmyun Noodle Soup,Pack,South Korea,3.75,NaN
2559,21,Nongshim,Champong Oriental Noodles,Pack,South Korea,4.00,NaN
2561,19,Nongshim,Shin Ramyun,Pack,South Korea,4.00,NaN
2567,13,Sapporo Ichiban,Chow Mein,Pack,Japan,5.00,2012 #4

Let us look at the served dishes in Taiwan and have rating above the average

In [113]:

ramen_df.loc[(ramen_df.Country == "Taiwan") & (ramen_df.Stars > mean)]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
65,2515,Uni-President,Man Han Feast Spicy Beef Flavor Instant Noodles,Bowl,Taiwan,5.00,NaN
68,2512,Mom's Dry Noodle,Dan Dan Noodle,Pack,Taiwan,5.00,NaN
79,2501,Happy Cook,Toona Paste Noodle,Pack,Taiwan,4.00,NaN
98,2482,TTL,Chicken With Chinese Shaoxing Wine,Pack,Taiwan,4.75,NaN
102,2478,Kiki Noodle,Scallion Oil & Soy Sauce Noodle,Pack,Taiwan,5.00,NaN
...,...,...,...,...,...,...,...
2331,249,Unif,100 Artificial Spicy Beef,Pack,Taiwan,3.75,NaN
2416,164,Unif / Tung-I,Artificial Beef Flavor,Pack,Taiwan,3.75,NaN
2428,152,Wu Mu,Steamed Noodle Garlic & Sesame Oil,Pack,Taiwan,4.50,NaN
2479,101,Ve Wong,Artificial Sesame Chicken,Pack,Taiwan,4.25,NaN
2512,68,Wei Lih,Jah Jan Mien Instant Noodle With Fried Soybean...,Pack,Taiwan,4.00,NaN

Get only the Brand and Style of these dishes

In [98]:
ramen_df.loc[(ramen_df.Country == "Taiwan") & (ramen_df.Stars > mean) , ["Brand" , "Style"]]

                 Brand Style
65       Uni-President  Bowl
68    Mom's Dry Noodle  Pack
79          Happy Cook  Pack
98                 TTL  Pack
102        Kiki Noodle  Pack
...                ...   ...
2331              Unif  Pack
2416     Unif / Tung-I  Pack
2428             Wu Mu  Pack
2479           Ve Wong  Pack
2512           Wei Lih  Pack

[136 rows x 2 columns]

HAVE a look at the served dishes at Finland and Sweden

In [112]:
ramen_df.loc[ramen_df.Country.isin(["Finland" , "Sweden"])]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
675,1905,Pirkka,Nuudeli Kana Nudlar Kyckling,Pack,Finland,3.50,NaN
816,1764,Pirkka,Nuudeli Tom Yum Katkarapu,Pack,Finland,3.75,NaN
856,1724,Pirkka,Nuudeli Liha Nudlar Kott,Pack,Finland,3.50,NaN
1026,1554,ICA,Asia Fast Noodles Snabbnudlar Räksmak,Pack,Sweden,3.00,NaN
1063,1517,Katoz,Instant Noodles Spicy Chili,Pack,Sweden,3.50,NaN
1093,1487,ICA,Asia Snabbnudlar Kycklingsmak,Pack,Sweden,3.25,NaN

Get the not null values in the top ten

In [118]:
ramen_df.loc[ramen_df["Top Ten"].notnull()]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
616,1964,MAMA,Instant Noodles Coconut Milk Flavour,Pack,Myanmar,5.00,2016 #10
633,1947,Prima Taste,Singapore Laksa Wholegrain La Mian,Pack,Singapore,5.00,2016 #1
655,1925,Prima,Juzz's Mee Creamy Chicken Flavour,Pack,Singapore,5.00,2016 #8
673,1907,Prima Taste,Singapore Curry Wholegrain La Mian,Pack,Singapore,5.00,2016 #5
752,1828,Tseng Noodles,Scallion With Sichuan Pepper Flavor,Pack,Taiwan,5.00,2016 #9
891,1689,Wugudaochang,Tomato Beef Brisket Flavor Purple Potato Noodle,Pack,China,5.00,2016 #7
942,1638,A-Sha Dry Noodle,Veggie Noodle Tomato Noodle With Vine Ripened ...,Pack,Taiwan,5.00,2015 #10
963,1617,MyKuali,Penang Hokkien Prawn Noodle (New Improved Taste),Pack,Malaysia,5.00,2015 #7
995,1585,CarJEN,Nyonya Curry Laksa,Pack,Malaysia,5.00,2015 #4
1059,1521,Maruchan,Gotsumori Sauce Yakisoba,Tray,Japan,5.00,2015 #9
1072,1508,Mamee,Chef Gold Recipe Mi Kari Seribu Rasa,Pack,Malaysia,5.00,2015 #6
1080,1500,MyKuali,Penang Red Tom Yum Goong Noodle,Pack,Malaysia,5.00,2015 #1
1109,1471,Mama,Instant Noodles Shrimp Creamy Tom Yum Flavour ...,Pack,Thailand,5.00,2013 #10
1114,1466,Mama,Oriental Style Instant Noodles Green Curry Fla...,Pack,Thailand,5.00,2015 #8
1230,1350,Mamee,Chef Curry Laksa Flavour,Pack,Malaysia,5.00,2014 #7
1250,1330,Sapporo Ichiban,Otafuku Okonomi Sauce Yakisoba,Tray,Japan,5.00,2014 #4
1272,1308,Nongshim,Soon Veggie Noodle Soup,Pack,South Korea,5.00,2014 #9
1278,1302,Mama,Instant Noodles Yentafo Tom Yum Mohfai Flavour,Pack,Thailand,5.00,2014 #10
1309,1271,Prima Taste,Singapore Chilli Crab La Mian,Pack,Singapore,5.00,2014 #8
1382,1198,Samyang Foods,Maesaengyitangmyun Baked Noodle,Pack,South Korea,5.00,2014 #5
1397,1183,Paldo,Cheese Noodle,Pack,South Korea,5.00,2014 #6
1493,1087,MyKuali,Penang White Curry Noodle,Pack,Malaysia,5.00,2014 #1
1588,992,Prima Taste,Singapore Laksa La Mian,Pack,Singapore,5.00,2013 #1
1589,991,Prima Taste,Singapore Curry La Mian,Pack,Singapore,5.00,2013 #2
1646,934,Nongshim,Jinjja Jinjja Flamin' Hot & Nutty,Pack,USA,5.00,2013 #4
1670,910,Paldo,Namja Ramyun,Bowl,South Korea,4.25,\n
1757,823,Paldo,Kokomen Spicy Chicken,Pack,South Korea,5.00,2013 #9
1846,734,Indomie,Mi Goreng Rasa Ayam Panggang Jumbo (Local),Pack,Indonesia,5.00,\n
1865,715,Indomie,Mi Goreng Rendang (Import),Pack,Indonesia,5.00,2013 #3
1972,608,Koka,Spicy Black Pepper,Pack,Singapore,5.00,2012 #10
2002,578,Nongshim,Shin Ramyun Black,Pack,South Korea,4.75,2012 #7
2146,434,Mi Sedaap,Kari Spesial,Pack,Indonesia,4.50,2012 #5
2188,392,Nissin,Yakisoba Noodles Karashi,Tray,Japan,5.00,2012 #3
2189,391,Myojo,Hyoubanya No Chukasoba Oriental,Pack,Japan,4.25,2012 #6
2248,332,Nongshim,Champong Oriental Noodles,Cup,South Korea,3.75,\n
2295,285,Doll,Artificial Chicken,Pack,Hong Kong,4.50,2012 #9
2475,105,Indomie,Special Fried Curly Noodle,Pack,Indonesia,5.00,2012 #1
2533,47,Indomie,Mi Goreng Jumbo Barbecue Chicken,Pack,Indonesia,5.00,2012 #2
2535,45,Indomie,Mi Goreng Sate,Pack,Indonesia,5.00,\n
2549,31,Myojo,Ippeichan Yakisoba,Tray,Japan,4.00,2013 #6
2567,13,Sapporo Ichiban,Chow Mein,Pack,Japan,5.00,2012 #4

Let us change a column values for example Review # column

In [119]:
ramen_df.loc[:,["Review #"]]= list(range(1,2578))

In [120]:
ramen_df["Review #"]

0          1
1          2
2          3
3          4
4          5
        ...
2575    2573
2576    2574
2577    2575
2578    2576
2579    2577
Name: Review #, Length: 2577, dtype: int64

# dropna()
   DROP the rows that contain nan

In [121]:
ramen_df.dropna()     # but this is not suitable for this data
                        #because the most of data will be dropped

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
616,615,MAMA,Instant Noodles Coconut Milk Flavour,Pack,Myanmar,5.00,2016 #10
633,632,Prima Taste,Singapore Laksa Wholegrain La Mian,Pack,Singapore,5.00,2016 #1
655,654,Prima,Juzz's Mee Creamy Chicken Flavour,Pack,Singapore,5.00,2016 #8
673,672,Prima Taste,Singapore Curry Wholegrain La Mian,Pack,Singapore,5.00,2016 #5
752,751,Tseng Noodles,Scallion With Sichuan Pepper Flavor,Pack,Taiwan,5.00,2016 #9
891,890,Wugudaochang,Tomato Beef Brisket Flavor Purple Potato Noodle,Pack,China,5.00,2016 #7
942,941,A-Sha Dry Noodle,Veggie Noodle Tomato Noodle With Vine Ripened ...,Pack,Taiwan,5.00,2015 #10
963,962,MyKuali,Penang Hokkien Prawn Noodle (New Improved Taste),Pack,Malaysia,5.00,2015 #7
995,993,CarJEN,Nyonya Curry Laksa,Pack,Malaysia,5.00,2015 #4
1059,1057,Maruchan,Gotsumori Sauce Yakisoba,Tray,Japan,5.00,2015 #9
1072,1070,Mamee,Chef Gold Recipe Mi Kari Seribu Rasa,Pack,Malaysia,5.00,2015 #6
1080,1078,MyKuali,Penang Red Tom Yum Goong Noodle,Pack,Malaysia,5.00,2015 #1
1109,1107,Mama,Instant Noodles Shrimp Creamy Tom Yum Flavour ...,Pack,Thailand,5.00,2013 #10
1114,1112,Mama,Oriental Style Instant Noodles Green Curry Fla...,Pack,Thailand,5.00,2015 #8
1230,1228,Mamee,Chef Curry Laksa Flavour,Pack,Malaysia,5.00,2014 #7
1250,1248,Sapporo Ichiban,Otafuku Okonomi Sauce Yakisoba,Tray,Japan,5.00,2014 #4
1272,1270,Nongshim,Soon Veggie Noodle Soup,Pack,South Korea,5.00,2014 #9
1278,1276,Mama,Instant Noodles Yentafo Tom Yum Mohfai Flavour,Pack,Thailand,5.00,2014 #10
1309,1307,Prima Taste,Singapore Chilli Crab La Mian,Pack,Singapore,5.00,2014 #8
1382,1380,Samyang Foods,Maesaengyitangmyun Baked Noodle,Pack,South Korea,5.00,2014 #5
1397,1395,Paldo,Cheese Noodle,Pack,South Korea,5.00,2014 #6
1493,1491,MyKuali,Penang White Curry Noodle,Pack,Malaysia,5.00,2014 #1
1588,1586,Prima Taste,Singapore Laksa La Mian,Pack,Singapore,5.00,2013 #1
1589,1587,Prima Taste,Singapore Curry La Mian,Pack,Singapore,5.00,2013 #2
1646,1644,Nongshim,Jinjja Jinjja Flamin' Hot & Nutty,Pack,USA,5.00,2013 #4
1670,1668,Paldo,Namja Ramyun,Bowl,South Korea,4.25,\n
1757,1755,Paldo,Kokomen Spicy Chicken,Pack,South Korea,5.00,2013 #9
1846,1844,Indomie,Mi Goreng Rasa Ayam Panggang Jumbo (Local),Pack,Indonesia,5.00,\n
1865,1863,Indomie,Mi Goreng Rendang (Import),Pack,Indonesia,5.00,2013 #3
1972,1970,Koka,Spicy Black Pepper,Pack,Singapore,5.00,2012 #10
2002,2000,Nongshim,Shin Ramyun Black,Pack,South Korea,4.75,2012 #7
2146,2144,Mi Sedaap,Kari Spesial,Pack,Indonesia,4.50,2012 #5
2188,2186,Nissin,Yakisoba Noodles Karashi,Tray,Japan,5.00,2012 #3
2189,2187,Myojo,Hyoubanya No Chukasoba Oriental,Pack,Japan,4.25,2012 #6
2248,2246,Nongshim,Champong Oriental Noodles,Cup,South Korea,3.75,\n
2295,2293,Doll,Artificial Chicken,Pack,Hong Kong,4.50,2012 #9
2475,2473,Indomie,Special Fried Curly Noodle,Pack,Indonesia,5.00,2012 #1
2533,2531,Indomie,Mi Goreng Jumbo Barbecue Chicken,Pack,Indonesia,5.00,2012 #2
2535,2533,Indomie,Mi Goreng Sate,Pack,Indonesia,5.00,\n
2549,2547,Myojo,Ippeichan Yakisoba,Tray,Japan,4.00,2013 #6
2567,2565,Sapporo Ichiban,Chow Mein,Pack,Japan,5.00,2012 #4

In [122]:
ramen_df.dropna(axis = 'columns')  #to delete the columns which contain nan

,Review #,Brand,Variety,Country,Stars
0,1,New Touch,T's Restaurant Tantanmen,Japan,3.75
1,2,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Taiwan,1.00
2,3,Nissin,Cup Noodles Chicken Vegetable,USA,2.25
3,4,Wei Lih,GGE Ramen Snack Tomato Flavor,Taiwan,2.75
4,5,Ching's Secret,Singapore Curry,India,3.75
...,...,...,...,...,...
2575,2573,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Vietnam,3.50
2576,2574,Wai Wai,Oriental Style Instant Noodles,Thailand,1.00
2577,2575,Wai Wai,Tom Yum Shrimp,Thailand,2.00
2578,2576,Wai Wai,Tom Yum Chili Flavor,Thailand,2.00
2579,2577,Westbrae,Miso Ramen,USA,0.50

IF we want to save the changes to the real data we should do
ramen_df.dropna(axis = 'columns' , inplace = True)

In [ ]:
ramen_df.dropna(subset = ['Style'])  #we use subset to define tha columns we want work on

In [123]:
ramen_df.loc[ramen_df['Style'].isnull()]

      Review #   Brand            Variety Style Country  Stars Top Ten
2152      2150  Kamfen     E Menm Chicken   NaN   China   3.75     NaN
2442      2440    Unif  100 Furong Shrimp   NaN  Taiwan   3.00     NaN

Filling tha Nan with values

In [124]:
ramen_df.fillna({"Style":"Not Available", "Top Ten":-1})

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,1,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,-1
1,2,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1.00,-1
2,3,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,-1
3,4,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,-1
4,5,Ching's Secret,Singapore Curry,Pack,India,3.75,-1
...,...,...,...,...,...,...,...
2575,2573,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.50,-1
2576,2574,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1.00,-1
2577,2575,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2.00,-1
2578,2576,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2.00,-1
2579,2577,Westbrae,Miso Ramen,Pack,USA,0.50,-1

In [131]:
ramen_df["Style"]=ramen_df["Style"].ffill()
ramen_df.iloc[[2152,2442] , : ]

      Review #          Brand       Variety Style Country  Stars Top Ten
2155      2153        Chikara   Shrimp Udon  Pack     USA   4.50     NaN
2445      2443  Unif / Tung-I  Fresh Shrimp  Pack  Taiwan   3.25     NaN

In [132]:
ramen_df["Style"].value_counts()

Style
Pack    1530
Bowl     481
Cup      450
Tray     108
Box        6
Can        1
Bar        1
Name: count, dtype: int64

In [139]:
import numpy as np
ramen_df["Stars"] = ramen_df["Stars"].replace('Unrated' , np.nan)
ramen_df["Stars"].dropna(inplace=True)
(ramen_df["Stars"].isnull()).value_counts()
ramen_df

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,1,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1.00,NaN
2,3,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,4,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,5,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN
...,...,...,...,...,...,...,...
2575,2573,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.50,NaN
2576,2574,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1.00,NaN
2577,2575,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2.00,NaN
2578,2576,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2.00,NaN
2579,2577,Westbrae,Miso Ramen,Pack,USA,0.50,NaN

In [140]:
ramen_df["Stars"]=ramen_df["Stars"].astype(float)

In [141]:
ramen_df

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,1,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1.00,NaN
2,3,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,4,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,5,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN
...,...,...,...,...,...,...,...
2575,2573,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.50,NaN
2576,2574,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1.00,NaN
2577,2575,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2.00,NaN
2578,2576,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2.00,NaN
2579,2577,Westbrae,Miso Ramen,Pack,USA,0.50,NaN

In [ ]:
df1=pd.DataFrame({ 'A' : ['A1','A2'] , 'B' : ['B1','B2'] ,'C' : ['C1','C2']})
df2=pd.DataFrame({ 'A' : ['A3','A4'] , 'B' : ['B3','B4'] ,'C' : ['C3','C4']})

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.

In [144]:
df1

    A   B   C
0  A1  B1  C1
1  A2  B2  C2

In [145]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4

In [ ]:
pd.concat([df1,df2] , ignore_index= True)     # == df1.append(df2 , ignore_index=True)

    A   B   C
0  A1  B1  C1
1  A2  B2  C2
2  A3  B3  C3
3  A4  B4  C4

## Describe

In [147]:
ramen_df.describe()

          Review #        Stars
count  2577.000000  2577.000000
mean   1289.000000     3.654676
std     744.060145     1.015331
min       1.000000     0.000000
25%     645.000000     3.250000
50%    1289.000000     3.750000
75%    1933.000000     4.250000
max    2577.000000     5.000000

In [151]:
ramen_df

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,1,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1.00,NaN
2,3,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,4,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,5,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN
...,...,...,...,...,...,...,...
2575,2573,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.50,NaN
2576,2574,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1.00,NaN
2577,2575,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2.00,NaN
2578,2576,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2.00,NaN
2579,2577,Westbrae,Miso Ramen,Pack,USA,0.50,NaN

## Transform

In [154]:
 #Now we want to get the mean of sales of each item
ramen_df["Brand_avg"] = ramen_df.groupby("Brand")["Stars"].transform("mean")
ramen_df

,Review #,Brand,Variety,Style,Country,Stars,Top Ten,Brand_avg
0,1,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN,4.277778
1,2,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1.00,NaN,2.750000
2,3,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN,3.918570
3,4,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN,3.450000
4,5,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN,3.812500
...,...,...,...,...,...,...,...,...
2575,2573,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.50,NaN,3.054545
2576,2574,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1.00,NaN,2.934000
2577,2575,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2.00,NaN,2.934000
2578,2576,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2.00,NaN,2.934000
2579,2577,Westbrae,Miso Ramen,Pack,USA,0.50,NaN,0.500000

# Pivot Tables

In [6]:
import seaborn as sns

In [7]:
titanic = sns.load_dataset("titanic")
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [8]:
titanic["who"].value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

In [9]:
titanic.pivot_table(index= "who",columns= "class" ,values= "age" ,aggfunc= "mean")

C:\Users\bebaa\AppData\Local\Temp\ipykernel_17384\4192593209.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table(index= "who",columns= "class" ,values= "age" ,aggfunc= "mean")

class      First     Second      Third
who
child   7.820000   4.543684   6.817586
man    42.382653  33.588889  28.995556
woman  35.500000  32.179688  27.854167

In [ ]:
# the percentage of survived females and males
titanic.pivot_table(index= "sex",values= "survived" ,aggfunc= "mean")

        survived
sex
female  0.742038
male    0.188908

In [11]:
titanic.pivot_table(index= "who",columns= "class" ,values=[ "age", "survived" ],aggfunc= "count")

C:\Users\bebaa\AppData\Local\Temp\ipykernel_17384\1003083166.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table(index= "who",columns= "class" ,values=[ "age", "survived" ],aggfunc= "count")

        age              survived
class First Second Third    First Second Third
who
child     6     19    58        6     19    58
man      98     90   225      119     99   319
woman    82     64    72       91     66   114

In [8]:
titanic.pivot_table(index= "who",columns= "class" ,values=[ "age", "survived" ], aggfunc= {"survived": "count" , "age":"mean"})

C:\Users\bebaa\AppData\Local\Temp\ipykernel_1676\3763721282.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table(index= "who",columns= "class" ,values=[ "age", "survived" ], aggfunc= {"survived": "count" , "age":"mean"})

             age                       survived
class      First     Second      Third    First Second Third
who
child   7.820000   4.543684   6.817586        6     19    58
man    42.382653  33.588889  28.995556      119     99   319
woman  35.500000  32.179688  27.854167       91     66   114

In [12]:
titanic.shape

(891, 15)

In [15]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [18]:
titanic["age"] = titanic["age"].fillna(titanic["age"].median())

In [19]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [20]:
titanic["embarked"] = titanic["embarked"].fillna(titanic["embarked"].mode()[0])

In [22]:
titanic["embark_town"] = titanic["embark_town"].fillna(titanic["embark_town"].mode()[0])

In [23]:
titanic = titanic.drop(columns=["deck"])

In [24]:
titanic.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64